name: Deploy React to cPanel Subdomain

on:
  push:
    branches:
      - main  # Runs on every push to the main branchs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies & Build React App
      run: |
        cd frontend_alumnisphere
        npm install
        npm run build

    - name: Setup SSH Connection
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.CPANEL_HOST }} >> ~/.ssh/known_hosts
        echo "SSH setup complete"

    - name: Debug SSH & Check Remote Path
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }} "ls -lah /home/sewturbhe/alumnisphere.vishalsharmadev.in/"

    - name: Deploy via Rsync
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" --delete frontend_alumnisphere/dist/ ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }}:/home/sewturbhe/alumnisphere.vishalsharmadev.in/
