name: Deploy React to cPanel Subdomain

on:
  push:
    branches:
      - main  # Runs on every push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies & Build React App
      run: |
        cd frontend_alumnisphere
        npm install
        npm run build

    - name: Deploy via SFTP
      run: |
        sudo apt-get install -y sshpass
        sshpass -p "${{ secrets.CPANEL_PASSWORD }}" sftp -o StrictHostKeyChecking=no ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }} <<EOF
          lcd frontend_alumnisphere/dist
          cd /home/sewturbhe/alumnisphere.vishalsharmadev.in/
          put -r *
          bye
        EOF
