name: Deploy React to cPanel Subdomain

on:
  push:
    branches:
      - main  # Runs on every push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies & Build React App
      run: |
        cd frontend_alumnisphere
        npm install
        npm run build

    - name: Deploy via SFTP
      run: |
        sudo apt-get install -y lftp
        lftp -c "
        open -u ${{ secrets.CPANEL_USERNAME }},${{ secrets.CPANEL_PASSWORD }} sftp://${{ secrets.CPANEL_HOST }};
        mirror -R frontend_alumnisphere/dist /home/sewturbhe/alumnisphere.vishalsharmadev.in/ --delete --verbose;
        bye
        "
